[package]
name = "faye_utils"
version = "0.1.0"
license = "MIT"
edition = "2018"
authors = ["Siegfried Wu <siegfried.wu@outlook.at>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
